services:
  semantic-search:
    platform: linux/amd64
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - semantic-search-db
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  semantic-search-db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: