# Generated by Django 4.1.13 on 2026-04-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpage",
            name="s3_key",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
