# Generated by Django 4.1.13 on 2026-03-31 06:48

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "authority_score",
                    models.FloatField(
                        db_index=True,
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-authority_score", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="documenttype",
            index=models.Index(fields=["name"], name="document_ty_name_8ea1f1_idx"),
        ),
        migrations.AddIndex(
            model_name="documenttype",
            index=models.Index(
                fields=["authority_score"], name="document_ty_authori_527924_idx"
            ),
        ),
    ]
