# Generated by Django 4.1.13 on 2026-03-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_chunk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="bounding_polygons",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
