# Generated by Django 4.1.13 on 2026-04-22 20:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("document_page", "0002_documentpage_s3_key"),
        ("document", "0001_initial"),
        ("document_chunk", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documentchunk",
            name="unique_chunk_per_page",
        ),
        migrations.RemoveIndex(
            model_name="documentchunk",
            name="document_ch_page_id_ae85f0_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentchunk",
            name="chunk_embedding_title_hnsw",
        ),
        migrations.RemoveIndex(
            model_name="documentchunk",
            name="chunk_embedding_doc_hnsw",
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="page",
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="section_type",
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="document",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="document.document",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="end_page",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks_end",
                to="document_page.documentpage",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="start_page",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks_start",
                to="document_page.documentpage",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="chunk_index",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="document_ch_documen_8e4d8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["start_page", "end_page"],
                name="document_ch_start_p_6d4e1f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                fields=("document", "chunk_index"),
                name="unique_chunk_per_document",
            ),
        ),
    ]
