# Generated by Django 4.1.13 on 2026-02-25 22:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import pgvector.django.indexes


class Migration(migrations.Migration):

    dependencies = [
        ("document_chunk", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentchunk",
            options={"ordering": ["chunk_index"]},
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="chunk_index",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="document_ch_documen_8e4d8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="chunk_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                fields=("document", "chunk_index"),
                name="unique_chunk_per_document",
            ),
        ),
    ]
