# Generated by Django 4.1.13 on 2026-02-27 00:20

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        (
            "document_chunk",
            "0002_alter_documentchunk_options_documentchunk_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
