# Generated by Django 4.1.13 on 2026-04-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_chunk", "0002_remove_documentchunk_unique_chunk_per_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="section_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
