# Generated by Django 4.1.13 on 2026-03-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="url",
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("PROCESSING", "PROCESSING"),
                    ("READY", "READY"),
                    ("FAILED", "FAILED"),
                ],
                default="PENDING",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="s3_key",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
