# Generated by Django 4.1.13 on 2026-03-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_session", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadsession",
            name="s3_key",
        ),
        migrations.AlterField(
            model_name="uploadsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("uploading", "Uploading"),
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
