name: Checks

on: [push]

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create CI env file
        run: |
          cat <<EOF > .env.ci
          DEBUG=False
          SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_URL=sqlite:///db.sqlite3
          EOF
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose run --rm semantic-search sh -c "python manage.py test --settings=app.settings_test"
      - name: Lint
        run: docker compose run --rm semantic-search sh -c "flake8"